services:
  - type: web
    name: rostar-notes-hub-api
    env: node
    plan: free
    branch: main
    root: .
    buildCommand: npm install && npm run build
    startCommand: npm run start:backend
    autoDeploy: true
